# Generated by Django 5.0.1 on 2024-01-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Информационное'), ('warning', 'Предупреждающее'), ('error', 'С ошибкой')], max_length=32, verbose_name='Тип уведомления'),
        ),
    ]
